version: '3'

services:
    app:
        image: streamlit-docker
        build:
            dockerfile: Dockerfile
        environment:
            - PORT=${PORT}
        ports:
            - ${PORT}:${PORT}
        volumes:
            - .:/app
            - ./ollama/ollama:/root/.ollama
            - ./mobilenet_model:/app/mobilenet_model
        container_name: ollama
        pull_policy: always
        tty: true
        restart: always